    <div class="tcr">
        <div>
            <div class="container" style="min-height:500px">
                <p class="tcr-first-para">T cells are the core components of our adaptive immune system. Once activated, they can directly kill cells that are foreign (cytolytic T-cells) or perform helper function (helper T-cells) to activate B-cells to make antibodies against foreign antigen. The activation of T-cells involve recognition of MHC-peptide complex by the T-cell receptors (TCR). We carry >109 T-cells, each expressing a unique TCR. This highly diverse repertoire of T-cells has the ability to recognize peptides originating from foreign elements such as invading pathogens and cancer cells. Each TCR recognize peptides in complex with MHC proteins presented on the surface of antigen presenting cells. Productive T-cell activation results in the clonal expansion of a specific T-cell and this expansion can be accurately determined by TCR sequencing. In cancer, TCR sequencing has predictive and prognostic value and can lead to the development of novel therapeutics such as engineered T-cells.</p>
                <p class="text-center"><img src="<?php echo $site_path;?>/services/tcr-sequencing.jpg" border="1"></p>
                <p>Source: <a href="http://www.ncbi.nlm.nih.gov/pmc/articles/PMC3979016/" target="_blank">Genome Med.</a> 2013; 5(10): 98.</p>
                <p class="tcr-last-para">Analysis of T-cell population requires generation of large quantity of data to cover each and every unique TCR expressed by T-cells present in the population. This is achieved by next generation sequencing of genomic DNA from purified T-cells. Both α and β chain of the TCR are sequenced to determine clonal diversity of the complementary-determining regions (CDRs) of the individual receptor. The CDR1 and CDR2 regions contribute binding to MHC and the CDR3 region to the peptide presented by the MHC. The diversity in the CDR3 region can be assessed by sequencing the β chain of the TCR complex.</p>
            </div>
        </div>
    </div>