<div class="container privacy-policy" style="">

    <div class="row">
            <strong>1. Acknowledgment and Acceptance of Terms</strong>
        <p>MedGenome Labs Ltd. is committed to protecting your privacy. This privacy
            statement sets forth our current privacy practices with regard to the information we
            collect when you interact with MedGenomeClaria.Com website. By accessing
            MedGenomeClaria.Com, you acknowledge and fully understand our privacy
            statement and freely consent to the information collection and use practices described
            in this privacy statement.
        </p><br>
        <strong>2. Information We Collect and How We Use It</strong>
            <p>MedGenome Labs Ltd. collects certain information from and about its users directly
            from our web server logs, the user, and using Cookies. When you visit our website,
            we may track information to administer the site and analyze its usage for the purpose
            of serving our visitors and customers better.</p><br>
        <strong>Cookies:</strong>
            <p>This site uses cookies – small text files that are placed on your machine to help the
            site provide a better user experience. In general, cookies are used to retain user
            preferences and provide anonymised tracking data to third party applications like
            Google Analytics.</p>
            <p>Cookies provide for a better browsing experience. However, you may prefer to
            disable cookies on this site and on others. The most effective way to do this is to
            disable cookies in your browser.</p>
            <p>We don’t sell the information collected by cookies, nor do we disclose the information
            to third parties, except where required by law</p><br>
        <strong>Google Analytics:</strong>
            <p>This website uses Google Analytics, a web analytics service provided by Google, Inc.
            (“Google”).</p>
            <p>Google Analytics uses “cookies,” which are text files placed on your computer, to
            help the website analyse how users use the site. The information generated by the
            cookie about your use of the website (including your IP address) will be transmitted to
            and stored by Google on its servers.</p>
            <p>Google will use this information for the purpose of evaluating your use of the website,
            compiling reports on website activity for website operators and providing other
            services relating to website activity and Internet usage.</p>
            <p>Google may also transfer this information to third parties where required to do so by
            law, or where such third parties process the information on Google’s behalf.</p>
            <p>Google will not associate your IP address with any other data held by Google.</p>

            <p>You may refuse the use of cookies by selecting the appropriate settings on your
            browser, however please note that if you do this you may not be able to use the full
            functionality of this website.</p>
            <p>By using this website, you consent to the processing of data about you by Google in
            the manner and for the purposes set out above. Please refer to the Google Advertising
            Privacy Notice for more information about tracking cookies for Google Adwords &
            Google Analytics.</p><br>
        <strong>Google Adwords Conversion Tracking:</strong>
            <p>This website uses Google AdWords conversion tracking features. This functionality
            enables us to understand visitor behavior on specific webpages and helps increase the
            website’s effectiveness for our visitors.</p><br>
        <strong>Google Adwords Remarketing:</strong>
            <p>This website uses Google AdWords remarketing code to log when users view specific
            pages or take specific actions on a website. This allows us to provide targeted
            advertising in the future. This could be in the form of an advertisement on the Google
            search results page, or a site in the Google Display Network. Third-party vendors,
            including Google, use cookies to serve ads based on someone’s past visits to this
            website. You can set preferences for how Google advertises to you using the Google
            Ad Preferences page, and if you want to you can opt out of interest-based advertising
            entirely by cookie settings.</p>
            <p>We will not disclose personally identifiable information we collect from you to third
            parties without your permission except to the extent necessary including:</p>
            <p>To fulfill your requests for services.</p>
            <p>To protect ourselves from liability.</p>
            <p>To respond to legal process or comply with law, or in connection with a merger,
            acquisition, or liquidation of the company.</p><br>

        <strong>3. Participating Clients, Merchant Policies, and Third Party Websites</strong>
            <p>Related services and offerings with links from this website, including all other
            websites, have their own privacy statements that can be viewed by clicking on the
            corresponding links within each respective website. MedGenome Labs Ltd. is not
            responsible for the privacy practices or contents of third-party or client websites. We
            recommend and encourage that you always review the privacy policies of merchants
            and other third parties before you provide any personal information or complete any
            transaction with such parties.</p><br>
        <strong>4. Changes to This Statement</strong>

            <p>MedGenome Labs Ltd. has the discretion to occasionally update this privacy
            statement. We encourage you to periodically review this privacy statement to stay
            informed about how we are helping to protect the personal information we collect.</p><br>
        <strong>5. Contacting Us</strong>
            <p>If you have questions regarding our Privacy Statement, its implementation, failure to
            adhere to this Privacy Statement and/or our general practices, please contact us at:
            <a href="mailto:help@medgenomeclaria.com">help@medgenomeclaria.com</p><br>
    </div>
</div>